version: '3'
services:
  web:
    image: httpd:2.4
    ports:
      - "8081:80"
    volumes:
      - ./js_app/public-html:/usr/local/apache2/htdocs/
    container_name: server-apache
    
  node-app:
    build: ./rest_app
    ports:
      - "8080:8080"
    volumes:
      - ./rest_app:/usr/src/app
    container_name: server-nodejs
    depends_on:
      - web

  grpc-app:
    build: ./grpc_app
    ports:
      - "3000:3000"
    volumes:
      - ./grpc_app:/usr/src/app
    container_name: server-grpc
    depends_on:
      - web
    hostname: address_arpc
  
  keycloak_web:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8085
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - keycloakdb
    ports:
      - 8085:8080
    hostname: keycloak

  keycloakdb:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
